spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/chat_message
    username: postgres
    password: 12345678
  mvc:
    log-request-details: true
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    web: DEBUG
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR
jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4bhdsfisdfsdjjUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
server:
  port: 80
  servlet:
    context-path: /api/v1